import React from 'react';
import { Activity, ShieldAlert } from 'lucide-react';

export const Footer = () => {
  return (
    <footer className="footer">
      <div className="footer-inner">
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'white', fontWeight: 'bold', marginBottom: '0.5rem' }}>
            <Activity size={20} color="#38bdf8" />
            <span>Agentic AI Multimodal Healthcare Assistant</span>
          </div>
          <p style={{ color: '#94a3b8', fontSize: '0.825rem', maxWidth: '480px' }}>
            B.Tech Final-Year Capstone Project. Designed as an educational and clinical decision-support assistant 
            orchestrated with specialized multi-agent AI systems.
          </p>
        </div>

        <div style={{ maxWidth: '420px', background: 'rgba(255,255,255,0.05)', padding: '0.75rem 1rem', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: '#fbbf24', fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.25rem' }}>
            <ShieldAlert size={14} /> Medical Notice
          </div>
          <p style={{ color: '#cbd5e1', fontSize: '0.75rem', lineHeight: 1.4 }}>
            For research & educational purposes only. Never disregard professional medical advice or delay seeking treatment 
            because of output generated by this application.
          </p>
        </div>
      </div>
      <div style={{ textAlign: 'center', marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid rgba(255,255,255,0.08)', fontSize: '0.775rem', color: '#64748b' }}>
        © 2026 Multimodal Agentic AI Healthcare System. All rights reserved.
      </div>
    </footer>
  );
};

