from .base_agent import BaseAgent
from ..services.ai_service import AIService


class MedicalInfoAgent(BaseAgent):
    """Specialized Agent responsible for translating clinical jargon into accessible layperson explanations and formulating doctor questions."""

    def __init__(self):
        super().__init__(
            name="MedicalInfoAgent",
            description="Explains medical terms, provides patient-friendly summaries, and formulates relevant questions for healthcare provider consultations."
        )

    # Built-in medical terminology glossary
    GLOSSARY = {
        'hemoglobin': {
            'term': 'Hemoglobin (Hb)',
            'layperson_explanation': 'An essential iron-containing protein inside your red blood cells that picks up oxygen in your lungs and carries it to all the cells and organs in your body.',
            'category': 'Hematology'
        },
        'white blood cells (wbc)': {
            'term': 'White Blood Cells (WBC / Leukocytes)',
            'layperson_explanation': 'The primary defensive cells of your immune system. Higher levels often signal that your body is fighting an infection or experiencing inflammation.',
            'category': 'Hematology'
        },
        'platelets': {
            'term': 'Platelets (Thrombocytes)',
            'layperson_explanation': 'Tiny disk-shaped blood cell fragments that stick together to form clots and plug microscopic leaks whenever a blood vessel is damaged.',
            'category': 'Hematology'
        },
        'fasting blood glucose': {
            'term': 'Fasting Blood Glucose',
            'layperson_explanation': 'The concentration of sugar circulating in your blood after fasting (not eating) for 8-12 hours. It is an important indicator of metabolic and insulin regulation.',
            'category': 'Metabolic'
        },
        'hba1c (glycated hemoglobin)': {
            'term': 'HbA1c',
            'layperson_explanation': 'A 3-month average of your blood glucose levels. Glucose attaches to hemoglobin over time, giving a stable picture of longer-term blood sugar trends.',
            'category': 'Metabolic'
        },
        'serum creatinine': {
            'term': 'Serum Creatinine',
            'layperson_explanation': 'A natural metabolic byproduct generated by working muscles. Healthy kidneys filter it out into urine; elevated blood levels suggest kidneys may be filtering less efficiently.',
            'category': 'Renal'
        },
        'blood urea nitrogen (bun)': {
            'term': 'Blood Urea Nitrogen (BUN)',
            'layperson_explanation': 'A waste product formed when your body digests proteins. It reflects hydration status and how effectively your kidneys are eliminating metabolic waste.',
            'category': 'Renal'
        },
        'total bilirubin': {
            'term': 'Total Bilirubin',
            'layperson_explanation': 'A yellowish pigment created during the normal recycling of old red blood cells. The liver processes it into bile; elevated levels can lead to jaundice.',
            'category': 'Hepatic'
        },
        'total cholesterol': {
            'term': 'Total Cholesterol',
            'layperson_explanation': 'A waxy, fat-like substance found throughout your body needed for hormone and cell membrane production, but excessive levels can contribute to arterial plaque buildup.',
            'category': 'Cardiovascular'
        },
        'cardiomegaly': {
            'term': 'Cardiomegaly',
            'layperson_explanation': 'An enlarged heart silhouette seen on imaging, which can occur due to prolonged hypertension, heart muscle thickening, or fluid around the pericardium.',
            'category': 'Cardiology'
        },
        'consolidation': {
            'term': 'Pulmonary Consolidation',
            'layperson_explanation': 'A radiological finding where normally spongy, air-filled areas of the lung become solidified by fluid, mucus, or inflammatory cells (commonly in pneumonia).',
            'category': 'Pulmonology'
        },
        'infiltrate': {
            'term': 'Pulmonary Infiltrate',
            'layperson_explanation': 'A localized area on an X-ray where foreign substances like inflammatory fluids have gathered in the lung tissue.',
            'category': 'Pulmonology'
        },
        'pleural effusion': {
            'term': 'Pleural Effusion',
            'layperson_explanation': 'An abnormal buildup of excess fluid between the layers of tissue that line the lungs and the chest wall.',
            'category': 'Pulmonology'
        }
    }

    def process(self, payload: dict) -> dict:
        report_findings = payload.get('report_findings', [])
        image_modality = payload.get('image_modality', '')
        abnormal_values = payload.get('abnormal_values', [])

        explanations = []
        identified_terms = set()

        # Match biomarkers and terms to explain
        for finding in report_findings:
            param_lower = finding.get('parameter', '').lower()
            for key, info in self.GLOSSARY.items():
                if key in param_lower or param_lower in key:
                    if info['term'] not in identified_terms:
                        explanations.append(info)
                        identified_terms.add(info['term'])

        # Check diagnostic keywords
        impressions = payload.get('clinical_impressions', [])
        for imp in impressions:
            kw_lower = imp.get('keyword', '').lower()
            if kw_lower in self.GLOSSARY and self.GLOSSARY[kw_lower]['term'] not in identified_terms:
                explanations.append(self.GLOSSARY[kw_lower])
                identified_terms.add(self.GLOSSARY[kw_lower]['term'])

        # If few terms matched, include general terminology
        if len(explanations) < 2:
            explanations.append(self.GLOSSARY['hemoglobin'])
            explanations.append(self.GLOSSARY['fasting blood glucose'])

        # Formulate patient doctor-consultation questions
        questions = [
            "Are there any specific lifestyle or dietary modifications you recommend based on these findings?",
            "Do any of the parameters marked outside the standard reference range require a repeat confirmatory test?",
            "How do these findings correlate with my current symptoms and physical exam?"
        ]

        if abnormal_values:
            abnormal_names = [a['parameter'] for a in abnormal_values[:2]]
            questions.insert(0, f"What might be contributing to my out-of-range {' and '.join(abnormal_names)} values?")

        if image_modality:
            questions.append(f"Does my {image_modality} suggest a need for any follow-up cross-sectional imaging (such as CT or ultrasound)?")

        plain_summary = (
            "This report summarizes key measurements of your body's biochemical and cellular indicators. "
            "Every individual has a unique baseline, so slight variations from standard laboratory intervals are common. "
            "Always consult your doctor to interpret these values in relation to your overall health and well-being."
        )

        return {
            'plain_language_summary': plain_summary,
            'terminology_explanations': explanations,
            'questions_for_doctor': questions,
            'advice_note': 'Write down these questions and bring a physical or digital copy of this report to your consultation.'
        }
